controllers:
    resource: ../src/Controller/
    type: annotation
kernel:
    resource: ../src/Kernel.php
    type: annotation

#app_lucky_number:
#    path : /lucky/number
#    controller : App\Controller\LuckyController::luckyNumber


#app_blog_list:
#    path : blog/{page<\d+>}
#    controller : App\Controller\BlogController::list
#    defaults:
#        page : 1